services:
  file:
    build:
      context: .
      target: builder
      args:
        - WATCH=1
    restart: unless-stopped
    command:
      - bash
      - -c
      - |
        cargo watch -s 'cargo run --profile dev'
    volumes:
      - ./src:/app/src
      - ./proto:/app/proto
      - ./tests:/app/tests
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
        minio:
          condition: service_healthy

  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      # MINIO_BUCKET: feur
      # MINIO_REGION: idf
      # MINIO_REGION_NAME: idf
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  minio_data:
